version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ForSa2025!SecurePass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-forsa}
      MYSQL_USER: ${MYSQL_USER:-forsa}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ForSa2025!AppPass}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - forsa-network

  app:
    build: .
    ports:
      - "80:3333"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${MYSQL_USER:-forsa}:${MYSQL_PASSWORD:-ForSa2025!AppPass}@db:3306/${MYSQL_DATABASE:-forsa}
      # Переменные для init-db.ts
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-forsa}
      DB_PASSWORD: ${MYSQL_PASSWORD:-ForSa2025!AppPass}
      DB_NAME: ${MYSQL_DATABASE:-forsa}
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "npm run init-db && node dist/index.js"
    restart: always
    networks:
      - forsa-network

volumes:
  db-data:

networks:
  forsa-network:
    driver: bridge
