version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-forsa}
      MYSQL_USER: ${MYSQL_USER:-forsa}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "80:3333"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${MYSQL_USER:-forsa}:${MYSQL_PASSWORD:-secret}@db:3306/${MYSQL_DATABASE:-forsa}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-forsa}
      DB_PASSWORD: ${MYSQL_PASSWORD:-secret}
      DB_NAME: ${MYSQL_DATABASE:-forsa}
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "npm run init-db && node dist/index.js"

volumes:
  db-data:
