version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-forsa_shop}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-LoremIpsum_95}
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads-data:/app/public/uploads:rw
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=forsa_shop
      - DB_USER=app_user
      - DB_PASSWORD=LoremIpsum_95
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=1d
      - VITE_BASE_URL=www.forsa-potolki.ru
    depends_on:
      - db
    command: npm run dev

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
      - uploads-data:/usr/share/nginx/html/uploads:ro
    command: >
      sh -c "nginx -g 'daemon off;'"

volumes:
  db-data:
  uploads-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/uploads
