version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-forsa}
      MYSQL_USER: ${MYSQL_USER:-forsa}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-secret}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${MYSQL_USER:-forsa}:${MYSQL_PASSWORD:-secret}@db:3306/${MYSQL_DATABASE:-forsa}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-forsa}
      DB_PASSWORD: ${MYSQL_PASSWORD:-secret}
      DB_NAME: ${MYSQL_DATABASE:-forsa}
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "sleep 10 && npm run init-db && node dist/index.js"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot-www:/var/www/certbot-www:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    command: >
      sh -c "nginx -g 'daemon off;'"

volumes:
  db-data:
